---

- hosts: localhost
  tasks:
   - name: install the latest version of Apache
     yum:
       name: httpd
       state: present
   - name: start the httpd service
     service: name=httpd state=started

   - name: Unarchive the files 
     unarchive:
       src: automation.tar.gz
       dest: /
       remote_src: yes

