FROM tomcat

MAINTAINER saurabh

RUN apt-get update && apt-get -y upgrade

WORKDIR /usr/local/tomcat

ADD tomcat-users.xml /usr/local/tomcat/conf 

RUN wget https://excellmedia.dl.sourceforge.net/project/pebble/pebble/2.6.4/pebble-2.6.4.zip  -O /usr/local/tomcat/pebble-2.6.4.zip

RUN unzip /usr/local/tomcat/pebble-2.6.4.zip -d /usr/local/tomcat/webapps

RUN cp /usr/local/tomcat/webapps/pebble-2.6.4/pebble-2.6.4.war  /usr/local/tomcat/webapps/

RUN rm -rf /usr/local/tomcat/pebble-2.6.4.zip 

EXPOSE 8080
